name: SVN to GitHub Migration

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.email "manilmunjal@gmail.com"
          git config --global user.name "manilmunjal"

      - name: Install Git and Git SVN
        run: |
          sudo add-apt-repository ppa:git-core/ppa -y
          sudo apt-get update
          sudo apt-get install -y git git-svn
          
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jfrog

      - name: Configure SVN credentials
        run: |
          echo "machine eu-subversion.assembla.com login manilmunjal password Mu@230841" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Ensure SVN directory structure and permissions
        run: |
          mkdir -p svn_repo/.svn/tmp
          sudo chmod -R 777 svn_repo/.svn/tmp

      - name: Clean up any previous SVN checkout
        run: |
          rm -rf svn_repo

      - name: Clone SVN repository with history
        run: |
          git svn clone https://eu-subversion.assembla.com/svn/anythingispossible^SVN.svn-demo/ svn_repo

      - name: Extract JFrog Artifactory URLs for binary files
        run: |
          cd svn_repo
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            jfrog_url="https://manilmunjalsneo.jfrog.io/artifactory/binary-store-generic-local/$binary_name"
            echo "$jfrog_url" > "$binary.url"
            git add "$binary.url"
          done

      - name: Upload binaries to JFrog Artifactory
        run: |
          cd svn_repo
          find . -type f \( -name "*.exe" -o -name "*.dll" -o -name "*.bin" \) | while read binary; do
            binary_name=$(basename "$binary")
            curl -u "manil.m@statusneo.com:Mu@230841" --upload-file "$binary" "https://manilmunjalsneo.jfrog.io/artifactory/binary-store-generic-local/$binary_name" || { echo "Failed to upload $binary to JFrog"; exit 1; }
          done

      - name: Commit and push to GitHub
        run: |
          cd svn_repo
          # Add all files excluding binaries
          find . -type f \( ! -iname "*.exe" -a ! -iname "*.dll" -a ! -iname "*.bin" \) -exec git add {} +
          
          # Commit URL pointers back to Git instead of binaries
          git commit -m "Initial commit with binaries moved to JFrog"
          
          # Add GitHub repository as remote
          git remote add github_repo https://github.com/manilmunjal/repo.git
          
          # Pull changes from the remote repository to integrate them
          git fetch github_repo
          git pull --rebase github_repo master

          # Push to GitHub
          git config --global credential.helper store
          git config --global user.email "manilmunjal@gmail.com"
          git config --global user.name "manilmunjal"
          echo "https://manilmunjal:${{secrets.PAT}}@github.com/manilmunjal/repo.git" > ~/.git-credentials
          git push --all github_repo
          git push --tags github_repo
